name: Java Maven Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn test --file pom.xml

      - name: Run tests
        run: test /Users/kangtaeheon/Desktop/multicampus/Github특강/java-maven-junit-skeleton/src/test/java/com/demo/JunitTest.java